/** My CVs arayüz metinleri — tek kaynak */
export const myCvsCopy = {
  pageTitle: 'My Resumes',
  pageSubtitle: 'Manage and optimize your professional profiles for any role.',
  filter: 'Filter',
  createNewCv: 'Create New CV',
  createNewTitle: 'Create New',
  createNewHint: 'Start with a fresh template or AI assistant',
  cvStrength: 'CV Strength',
  optimizeForCompany: 'Optimize for Company',
  recentlyEdited: 'Recently Edited',
  visibilityTitle: 'Profile Visibility Insights',
  aiRecTitle: 'AI Recommendation',
  fixNow: 'Fix Now',
  assistantTooltip: 'Ask CareerAI Assistant',
  assistantAria: 'Open CareerAI Assistant',
  editAria: 'Edit CV',
  downloadAria: 'Download CV',
  moreAria: 'More options',
  searchPlaceholder: 'Search your CVs...',
} as const;
