/** Dashboard arayüz metinleri — tek kaynak */
export const dashboardCopy = {
  brandName: 'CareerAI',
  accountLabel: 'Pro Account',
  searchPlaceholder: 'Search CVs, roles...',
  createCvCta: 'Create New CV',
  helpCenter: 'Help Center',
  logout: 'Logout',
  mobileMenuAria: 'Open navigation menu',
  notificationsAria: 'Notifications',
  viewAll: 'View All',
  recentActivityTitle: 'Recent Activity',
  applyAiOptimization: 'Apply AI Optimization',
  updateProfile: 'Update Profile',
  profileScoreLabel: 'Profile Score',
  footerCopyright: '© 2024 CareerAI Platforms Inc.',
  privacyPolicy: 'Privacy Policy',
  termsOfService: 'Terms of Service',
  cookies: 'Cookies',
  aiAssistantAria: 'Open AI Assistant',
} as const;
