/** AI CV Builder metinleri */
export const aiCvBuilderCopy = {
  resumeDetails: 'Resume Details',
  cvStrength: 'CV Strength',
  personalInformation: 'Personal Information',
  firstName: 'First Name',
  lastName: 'Last Name',
  fullName: 'Full Name',
  title: 'Title / Role',
  email: 'Email',
  phone: 'Phone',
  country: 'Country',
  city: 'City',
  portfolio: 'Portfolio',
  github: 'GitHub',
  linkedin: 'LinkedIn',
  about: 'Summary / About',
  aboutAi: 'AI Generate',
  workExperience: 'Work Experience',
  add: 'Add',
  jobTitle: 'Job Title',
  company: 'Company',
  startDate: 'Start Date',
  endDate: 'End Date',
  description: 'Description',
  aiImprove: 'AI Improve',
  education: 'Education',
  university: 'University',
  department: 'Department / Degree',
  skills: 'Skills',
  addSkill: '+ Add Skill',
  skillsAi: 'AI from Experience',
  languages: 'Languages',
  language: 'Language',
  level: 'Level',
  addLanguage: 'Add Language',
  languageSelect: 'CV Language',
  fontSizeSelect: 'Yazı Boyutu',
  fontSizeBody: 'İletişim / gövde (10–11 pt)',
  fontSizeName: 'Ad soyad (22 pt)',
  fontSizeProfileTitle: 'Ünvan / başlık (14 pt)',
  fontSizeHeading: 'Ana bölüm başlığı (14–16 pt)',
  fontSizeJobTitle: 'İş unvanı (12–13 pt)',
  fontSizeSkills: 'Yetenekler (10–11 pt)',
  fontSizeHint:
    'Ad soyad 22 pt ve ünvan 14 pt sabittir. İletişim/gövde ve yetenekler 10–11 pt, iş unvanı 12–13 pt, ana bölüm başlığı 14–16 pt.',
  skillsStyleSelect: 'Skills Style',
  languagesStyleSelect: 'Languages Style',
  badgeStylePlain: 'Plain',
  badgeStyleBadge: 'Badge',
  uploadTitle: 'Upload CV & Auto-fill',
  uploadHint: 'Upload a PDF; AI will analyze and fill the form.',
  chooseFile: 'Choose File',
  analyzeAi: 'Auto-fill with AI',
  analyzing: 'AI analyzing...',
  zoomIn: 'Zoom In',
  zoomOut: 'Zoom Out',
  exportPdf: 'Export PDF',
  share: 'Share',
  saveCv: 'Kaydet',
  savingCv: 'Kaydediliyor...',
  saveSuccess: 'CV kaydedildi.',
  saveError: 'CV kaydedilemedi.',
  aiAssistant: 'AI Writing Assistant',
  improveBullet: 'Improve this bullet point',
  suggestSummary: 'Suggest professional summary',
  fixGrammar: 'Fix grammar & tone',
  currentSuggestion: 'Current Suggestion',
  suggestionText:
    'Consider using stronger action verbs like "Architected" or "Orchestrated" instead of "Managed".',
  newTitle: 'AI CV Builder — New',
  editTitle: 'AI CV Builder — Edit',
  searchTemplates: 'Search templates...',
  notFound: 'CV not found in dummy store.',
} as const;
