/** AI CV Builder metinleri */
export const aiCvBuilderCopy = {
  resumeDetails: 'Resume Details',
  cvStrength: 'CV Strength',
  personalInformation: 'Personal Information',
  firstName: 'First Name',
  lastName: 'Last Name',
  fullName: 'Full Name',
  title: 'Title / Role',
  email: 'Email',
  phone: 'Phone',
  country: 'Country',
  city: 'City',
  portfolio: 'Portfolio',
  github: 'GitHub',
  linkedin: 'LinkedIn',
  about: 'Summary / About',
  aboutAi: 'AI Generate',
  workExperience: 'Work Experience',
  add: 'Add',
  jobTitle: 'Job Title',
  company: 'Company',
  startDate: 'Start Date',
  endDate: 'End Date',
  description: 'Description',
  aiImprove: 'AI Improve',
  education: 'Education',
  university: 'University',
  department: 'Department / Degree',
  skills: 'Skills',
  addSkill: '+ Add Skill',
  skillsAi: 'AI from Experience',
  languages: 'Languages',
  language: 'Language',
  level: 'Level',
  addLanguage: 'Add Language',
  languageSelect: 'CV Language',
  uploadTitle: 'Upload CV & Auto-fill',
  uploadHint: 'Upload a PDF; AI will analyze and fill the form.',
  chooseFile: 'Choose File',
  analyzeAi: 'Auto-fill with AI',
  analyzing: 'AI analyzing...',
  zoomIn: 'Zoom In',
  zoomOut: 'Zoom Out',
  exportPdf: 'Export PDF',
  share: 'Share',
  aiAssistant: 'AI Writing Assistant',
  improveBullet: 'Improve this bullet point',
  suggestSummary: 'Suggest professional summary',
  fixGrammar: 'Fix grammar & tone',
  currentSuggestion: 'Current Suggestion',
  suggestionText:
    'Consider using stronger action verbs like "Architected" or "Orchestrated" instead of "Managed".',
  newTitle: 'AI CV Builder — New',
  editTitle: 'AI CV Builder — Edit',
  searchTemplates: 'Search templates...',
  notFound: 'CV not found in dummy store.',
} as const;
